import { Antic } from "next/font/google";
import { Toaster } from "react-hot-toast";

import "../styles/globals.css";
import SessionAuthProvider from "<app>/context/SessionAuthProvider";
import QueryClientProvider from "<app>/providers/QueryClientProvider";

const antic = Antic({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "e-Bank | Your Bank",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${antic.className} flex flex-col items-center overflow-hidden`}
      >
        <SessionAuthProvider>
          <QueryClientProvider>
            {children}
            <Toaster />
          </QueryClientProvider>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
